sudo: required
services:
  - docker

before_install:
  - docker build -t souphianebensalim/docker-aws -f Dockerfile.dev .

script:
  - docker run souphianebensalim/docker-aws npm run test -- --coverage